### ISSUE TITLE
Bug with frame size that is not power of 2

### ISSUE THREAD

**Issue by amantalion** [kooBH/STFT#4]
I was wondering if you could help me to debug the following issue: if I set the frame size that is not a power of 2 I get a segmentation fault on the following line: 

https://github.com/kooBH/STFT/blob/1b8eb2a6954660f7921e1564d56f85c937c3d062/cpp/Ooura_FFT.h#L883

For example, if I set the frame size to 320, and the shift size to 160 I get a segmentation fault. Please, could you help me to fix this issue? Any help will be greatly appreciated.

**Comment by amantalion** [comment]
I think it might be because FFT requires the power of 2. So this issue might possibly be solved with padding.

**Comment by kooBH** [comment]
Most of FFT algorithms requires frame size as power of 2.  Yes, padding is good solution.

**Comment by amantalion** [comment]
Hi @kooBH. Thank you for your answer. Do you know by any chance how to properly pad the buffer with zeros? Can I just append zeros at the end of the buffer like that:

```
#include "cpp/STFT.h"
#include "WAV/WAV.h"

int main(){

  int ch = 1;
  int rate = 16000;
  int frame = 512;
  int shift = 256;
  int length;

  WAV input;
  WAV output(ch,rate);
  STFT process(ch,frame,shift);

  input.OpenFile("input.wav");
  output.NewFile("output.wav");

  short buf_in[ch*shift];
  double **data;
  short buf_out[ch*shift];

  data = new double*[ch];
  for(int i=0;i<ch;i++){
    data[i] = new double[frame+2];
    memset(data[i],0,sizeof(double)*(frame+2));
  }

  while(!input.IsEOF()){
    length = input.ReadUnit(buf_in,160*ch);
    for (size_t i = 160; i < 256; ++i) {
        buf_in[i] = (short int)0;
    }
    process.stft(buf_in,length,data);
    process.istft(data,buf_out);
    output.Append(buf_out,160*ch);
  }

  for(int i=0;i<ch;i++)
    delete[] data[i];
  delete[] data;

  return 0;
}
```
Thank you so much for your help again.

**Comment by kooBH** [comment]
I guess  as you did 
```cpp
for (size_t i = 160; i < 256; ++i) {
        buf_in[i] = (short int)0;
    }
```
padding on the end of the buffer is proper way.    

https://www.bitweenie.com/listings/fft-zero-padding/  

and if you pad on end of time domain buffer. like

```MATLAB
fs = 16000;
t = linspace(0,1,256);

x1 = sin(2*pi*fs*t);
figure;specgram(x1);title('x1');caxis([-80 20])

x2 = zeros(1,256);
x2(1:160) = x1(1:160); 

figure;specgram(x2);title('x2');caxis([-80 20])

```

![image](https://user-images.githubusercontent.com/39723411/110282856-8a273200-8022-11eb-8b7c-d13380dda7c5.png)

you can see, though the scale might be different, the struct is maintained.
